const shopProducts = [
    {
      _id: "1",
      name: "Product 1",
      price: 50,
      brand: "Brand A",
      availableQuantity: 10,
      image: "https://cdn.britannica.com/77/170477-050-1C747EE3/Laptop-computer.jpg",
      rating: 4,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    },
    {
      _id: "2",
      name: "Product 2",
      price: 80,
      brand: "Brand B",
      availableQuantity: 5,
      image: "https://cdn.britannica.com/77/170477-050-1C747EE3/Laptop-computer.jpg",
      rating: 5,
      description: "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    },
    {
      _id: "3",
      name: "Product 3",
      price: 100,
      brand: "Brand C",
      availableQuantity: 3,
      image: "https://cdn.britannica.com/77/170477-050-1C747EE3/Laptop-computer.jpg",
      rating: 3,
      description: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip.",
    },
    {
      _id: "4",
      name: "Product 4",
      price: 130,
      brand: "Brand C",
      availableQuantity: 3,
      image: "https://cdn.britannica.com/77/170477-050-1C747EE3/Laptop-computer.jpg",
      rating: 4,
      description: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    },
    {
      _id: "5",
      name: "Product 5",
      price: 200,
      brand: "Brand C",
      availableQuantity: 3,
      image: "https://cdn.britannica.com/77/170477-050-1C747EE3/Laptop-computer.jpg",
      rating: 3,
      description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
    {
      _id: "6",
      name: "Product 6",
      price: 1000,
      brand: "Brand C",
      availableQuantity: 3,
      image: "https://cdn.britannica.com/77/170477-050-1C747EE3/Laptop-computer.jpg",
      rating: 3,
      description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
    },
    {
      _id: "7",
      name: "Product 7",
      price: 900,
      brand: "Brand C",
      availableQuantity: 3,
      image: "https://cdn.britannica.com/77/170477-050-1C747EE3/Laptop-computer.jpg",
      rating: 3,
      description: "Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    },
    {
      _id: "8",
      name: "Product 8",
      price: 890,
      brand: "Brand C",
      availableQuantity: 3,
      image: "https://cdn.britannica.com/77/170477-050-1C747EE3/Laptop-computer.jpg",
      rating: 3,
      description: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    },
    {
      _id: "9",
      name: "Product 9",
      price: 770,
      brand: "Brand C",
      availableQuantity: 3,
      image: "https://cdn.britannica.com/77/170477-050-1C747EE3/Laptop-computer.jpg",
      rating: 3,
      description: "Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    },
  ];
  
  export default shopProducts;
  